### ISSUE TITLE
How you make jitter aa in last update? 

### ISSUE THREAD

**Issue by DeHaker** [superyor/RageSU#10]
Hi! Can you say how to make this aa: https://www.youtube.com/watch?time_continue=13&v=WhCdg-N7OhM&feature=emb_title

**Comment by superyor** [comment]
This is not possible anymore, that antiaim was done using the legacy features, if you need to break resolvers you can use lagsync.
If enough people want it I will add back the legacy features.

**Comment by DeHaker** [comment]
ot v3 fixing lagsync from 1-4 bullets with scout

**Comment by superyor** [comment]
Im still working on improving lagsync. I'll add back the rotation sway but with an improved algorithm.

**Comment by DeHaker** [comment]
Ok, thank you for best lua.
