### ISSUE TITLE
Crash on Load

### ISSUE THREAD

**Issue by akasyff** [superyor/RageSU#12]
**Describe the bug**
as soon as i load the lua game crashes

**To Reproduce**
1. paste the lua in
2. load the lua
3.crash
4.see error

**Expected behavior**
i expected it to not crash

**Screenshots**
---------------------------
Error
---------------------------
Game crashed!

Error: 0xc0000005
Address: 0x20ae0000 + 0x1a6199

EAX: 0x14cbf2c0
ECX: 0x0
EDX: 0x4181e377
EBX: 0x44e2b8
ESP: 0x44dee0
EBP: 0x44df60
ESI: 0x14cbf2c8
EDI: 0x44e2b8

0x20ae0000 + 0x2b658a
0x20ae0000 + 0x1a638f
0x20ae0000 + 0x256f89
0x20ae0000 + 0x255724
0x20ae0000 + 0xf4320
0x20ae0000 + 0x1a638f
0x20ae0000 + 0x19f5d0
0x20ae0000 + 0x2c7ddb
0x20ae0000 + 0x11faeb
0x20ae0000 + 0x1a638f
0x20ae0000 + 0x155c8e
0x20ae0000 + 0x29f1f3
0x20ae0000 + 0x87b81
0x20ae0000 + 0xf8320
0x20ae0000 + 0x271b0f
0x20ae0000 + 0x2d4385
tier0.dll + 0x2740
tier0.dll + 0x2740
engine.dll + 0x128862
ntdll.dll + 0x3299d
tier0_s.dll + 0x13000
user32.dll + 0x162fa
tier0_s.dll + 0x16e57
user32.dll + 0x16d91
tier0_s.dll + 0x16e57
ntdll.dll + 0x2e40c
steamclient.dll + 0x28203f
aswhook.dll + 0x2c73
aswhook.dll + 0x88c0
aswhook.dll + 0x2d6d
ntdll.dll + 0x1f8e1
KernelBase.dll + 0x115ce

Post this information on our forums using CTRL+C.
---------------------------
OK   
---------------------------
.

**Additional context**
Might be due to computer not getting all chars when copy pasting

**Comment by superyor** [comment]
Try to paste it in a text editor instead of the cheats editor.
This is a cheat issue, that's the least I can do.

**Comment by akasyff** [comment]
> Try to paste it in a text editor instead of the cheats editor.
> This is a cheat issue, that's the least I can do.

Yes! i sat and tested different things yesterday, i tried downloading directly from github, but the crashes still kept happening, so i tried pressing the run button in the texteditor inside the menu, and it worked! feels really weird and havent seen anyone else with this problem so might just be me.

**Comment by superyor** [comment]
Ok, gonna close this now then.
