### ISSUE TITLE
Crash when trying to load lua

### ISSUE THREAD

**Issue by stxrm-cc** [superyor/RageSU#13]
---------------------------
Error
---------------------------
Process crashed!

Error: 0xc0000005
Address: 0x67750000 + 0x25ef44

EAX: 0x2dd38b28
ECX: 0x0
EDX: 0x2
EBX: 0x4ce2e0
ESP: 0x4cdf10
EBP: 0x4cdf90
ESI: 0x2dd38b30
EDI: 0x4ce2e0

0x67750000 + 0x2c9f10
0x67750000 + 0x25f13a
0x67750000 + 0x215599
0x67750000 + 0x14fb8d
0x67750000 + 0x97d48
0x67750000 + 0x25f13a
0x67750000 + 0x296218
0x67750000 + 0x6642d
0x67750000 + 0x2980c2
0x67750000 + 0x25f13a
0x67750000 + 0xbcfc2
0x67750000 + 0x59d51
0x67750000 + 0xd4054
0x67750000 + 0x102af6
0x67750000 + 0x2a7ee7
0x67750000 + 0xfa70
0x67750000 + 0xa2bb
0x67750000 + 0x946c2
tier0.dll + 0x2740
tier0.dll + 0x2740
engine.dll + 0x128ab2
KernelBase.dll + 0x34dc8
user32.dll + 0x162fa
tier0_s.dll + 0x16fb7
tier0_s.dll + 0x16fb7
ntdll.dll + 0x2e434
steamclient.dll + 0x2878ff
steamclient.dll + 0x3e9a4b
user32.dll + 0x2794a
ntdll.dll + 0x74dcd
ntdll.dll + 0x2e434
ntdll.dll + 0x2e192

Post this information on our forums using CTRL+C.
---------------------------
OK   
---------------------------

**Comment by stxrm-cc** [comment]
I found a fix, probably temporary or only for my pc, but for it not to crash, open the edit feature in the lua tab and next to the save button uptop, there is the run button, when I clicked it, it didn't crash, so it's probably a cheat-side problem.

**Comment by superyor** [comment]
Yeah it's caused by the cheat. Load through the editor.
