### ISSUE TITLE
Choke on shot for Grenades and Knifes and Zeus

### ISSUE THREAD

**Issue by nazexd** [superyor/RageSU#16]
I don't know if choke on shot for grenades and knifes etc. is needed, but i dont see any sense in having that and its just a disadvantage i think. it would be nice to either have an option to disable the chokeon shot for grenades, knife and zeus. it would also be nice to select only auto for choke on shot and not scout etc. like choke on shot but not for every weapon

**Comment by superyor** [comment]
I'll disable it for grenades etc., don't know if im gonna make that for each weapon function though.

**Comment by nazexd** [comment]
it doesnt have to be implemented into the lua at all, since its possible to do externally just with changing gui values using an other lua. but some people arent able to do that. but i dont think so many people are obsessed with choke on shot like me lol

**Comment by superyor** [comment]
As of update 5.0/1.3, choke shot is disabled for grenades.
