### ISSUE TITLE
Revolver

### ISSUE THREAD

**Issue by nazexd** [superyor/RageSU#17]
Dont know if thats a bug but when i use an r8 my aa goes into helicopter mode. just see for urself. also wheres the fake position indicator from the stream? like on the ground where the fake is not the aa indicator.

**Comment by superyor** [comment]
I'll look into that R8 issue, the indicator is on the forums, just search antiaim angle lines.

**Comment by nazexd** [comment]
seems like the r8 problem vanished. will tell if it occurs again.

**Comment by superyor** [comment]
After further investigation, the revolver problem happens with Choke shot being enabled, I'll push a fix soon.

**Comment by superyor** [comment]
As of update 5.0/1.3, revolver is no longer going to work in choke shot which fixes the issue.
