### ISSUE TITLE
Stuck loading

### ISSUE THREAD

**Issue by Tuffs713** [superyor/RageSU#19]
**Describe the bug**
Stuck on loading???

**To Reproduce**
I load RageSU
It's stuck loading

**Expected behavior**
Stuck Loading

**Screenshots**
Picture RagSU loading thing but not loading all the way

**Comment by superyor** [comment]
Go into your aimware config folder and delete the modules folder.

**Comment by superyor** [comment]
Closed due to no response if the issue for resolved.
