### ISSUE TITLE
menu glitch

### ISSUE THREAD

**Issue by MrXTC** [superyor/RageSU#21]
**Explanation**
When I load ragesu I can't unload it and the menu is glitched idk but there are buttons everywhere and I can't do anything except to restart AIMWARE or just play without ragesu

**how to trigger the glitch**
1. go to settings
2. go to load luas
3. load the lua "ragesu", "ragesu Downloader"

**Expected behavior**
I want this to get fixed and that I can play normaly .

**Screenshot**

https://pasteboard.co/JalKjbn.png

**Additional context**
I would be happy if you fix my problem

**Comment by superyor** [comment]
Try resetting the lua state in the lua tab.

**Comment by MrXTC** [comment]
It's still glitched

**Comment by superyor** [comment]
> It's still glitched

I'll find some sort of fix soon

**Comment by superyor** [comment]
Closed because it will be fixed in the new recode.
