### ISSUE TITLE
RageSU ErrorMsg when loaded

### ISSUE THREAD

**Issue by ticzz** [superyor/RageSU#22]
When u load ragesu u get this message ![MHavdol](https://user-images.githubusercontent.com/32612882/85934762-07bd6e80-b8e8-11ea-88ea-d7892b00ca85.png)

Logs:
Crashdump: `http://xup.in/dl,17189933`
Newestlog: `http://xup.in/dl,99206342`

It seems that it works but finally its only u who knows if it still works or not.

or is it canceled somehow,  because over last time u wasn´t present in forum that much like u was few weeks ago..?

**Comment by superyor** [comment]
I have taken a break from coding/scripting and I didn't want to come back yet due to me starting a new competitive game and I don't want to risk a ban, however I'm gonna fix it soon.

**Comment by ticzz** [comment]
ah ok. thank you for fast response..
sad but wish u best luck anyways :D

**Comment by superyor** [comment]
Closed because recoding.
