### ISSUE TITLE
Stuck on loading 

### ISSUE THREAD

**Issue by SupSupSupxD** [superyor/RageSU#23]
**Describe the bug**
All it does when i press load is just put a text with loading and then its stuck there 

**To Reproduce**
press load on lua 

**Expected behavior**
The lua to load 

**Screenshots**
https://gyazo.com/cfeee9a12e603ce26e21137e03c23060

**Additional context**

**Comment by R4FA-1337** [comment]
I have the same problem

**Comment by superyor** [comment]
Currently Recoding, please wait till the recode is done.
